# Usage of Numpy In Data Science:
            NumPy is a fundamental package for numerical computation in Python and is widely used in data science.Numpy helps to manipulate,aggregate and the data.NumPy also provides powerful tools for working with arrays.Numpy Here are some of the basic functionalities of NumPy that are essential in data science:

For using numpy firstly we have to import the numpy package as we want.Here i'm importing it as np:

In [6]:
import numpy as np

## Creating Arrays:
             NumPy offers a variety of methods to create arrays, each suited for different use cases. Here are some of the most common ways to create arrays in NumPy:
##### 1.From Lists or Tuples:

In [9]:
#creating array using lists
array_lists=([1,2,3,4])
#creating array using tupes
array_tuples=((7,8,9,6))
print(array_lists)
print(array_tuples)

[1, 2, 3, 4]
(7, 8, 9, 6)


##### 2.Using arange():

Creating Arrays with a Range of Values: Similar to Python's range() but returns an array with the defined step difference,in the below example step=2.

In [11]:
array = np.arange(0, 10, 2)
print(array)

[0 2 4 6 8]


##### 3.Using linspace():

Evenly Spaced Values Over a Specified Interval: Generate a specified number of evenly spaced values between a start and an end value.

In [14]:
array = np.linspace(0, 10, 10)
print(array)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


##### 4.Using zeros(),ones():

Arrays Filled with Zeros,Ones: Create an array of specified shape filled with zeros,ones.

In [18]:
#creating array with Zeros
array_0 = np.zeros((3,3))
#creating array with ones
array_1 = np.ones((2,3))
print("array with zeros:")
print(array_0)
print("array with ones:")
print(array_1)

array with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array with ones:
[[1. 1. 1.]
 [1. 1. 1.]]


##### 5.Using empty():

Uninitialized Arrays: Create an array without initializing its values (contains whatever values are in memory at that location).

In [20]:
empty_array = np.empty((2, 2))
print(empty_array)

[[ 2.5  5. ]
 [ 7.5 10. ]]


##### 6.Using eye():

Identity Matrix: Create a 2D identity matrix (a square matrix with ones on the diagonal and zeros elsewhere).

In [21]:
identity_matrix = np.eye(3)  
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 7.Using full():

Arrays Filled with a Specific Value: Create an array of a specified shape filled with a specified value.

In [22]:
full_array = np.full((2, 3), 7)  
print(full_array)

[[7 7 7]
 [7 7 7]]


##### 8.Using random Module:

Random Arrays: Generate arrays filled with random numbers.

In [24]:
#Uniform Distribution: Random values between 0 and 1
random_array = np.random.rand(3, 3)  
print(random_array)

[[0.07376425 0.03768713 0.92046786]
 [0.75936484 0.62784486 0.10314081]
 [0.09341568 0.15981832 0.06305429]]


In [25]:
#Normal Distribution: Random values from a normal (Gaussian) distribution
normal_array = np.random.randn(3, 3)
print(normal_array)

[[-0.34721449  0.05060423 -0.22506696]
 [-1.44770182  0.82545616  0.22525486]
 [ 0.60569999  0.41342593 -0.96006834]]


In [26]:
#Random Integers: Random integers between specified bounds
random_integers = np.random.randint(1, 10, size=(3, 3))
print(random_integers)

[[2 7 2]
 [9 2 7]
 [5 2 7]]


##### 9.Using diag():

Diagonal Arrays: Create a diagonal array with specified values on the diagonal.

In [27]:
diag_array = np.diag([1, 2, 3, 4])  
print(diag_array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


##### 10.Using tile()

Repeating Arrays: Repeat an array a specified number of times

In [32]:
base_array = np.array([1, 2, 3])
# Repeats the base array 2 times along the row and 3 times along the column
tiled_array = np.tile(base_array, (2, 3))
print(tiled_array)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


##### Creating multidimensional array:
Numpy multidimentional arrays can be created using nested lists or by using the arr.reshape() function.

In [7]:
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Manipulation Of Data:

#### Reshaping Array:
##### 1.reshape():

Reshape an Existing Array: Change the shape of an existing array without changing its data

In [36]:
array = np.arange(6)
reshaped_array = array.reshape((2, 3))
# Reshape to a 2x3 array
print(reshaped_array)

[[0 1 2]
 [3 4 5]]


##### 2.flatten():

Flatten: Convert a multi-dimensional array to a 1D array

In [37]:
flatten_arr = reshaped_array.flatten()
print(flatten_arr)

[0 1 2 3 4 5]


#### Matrix Operations:
##### 1.transpose():

Transpose: Transpose a matrix (swapping rows and columns)

In [38]:
transposed_array = reshaped_array.T 
print(transposed_array)

[[0 3]
 [1 4]
 [2 5]]


##### 2.trace():

Trace of a matrix:calculates the sum of the diagonal elements.

In [43]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
trace_of_a_matrix = np.trace(array)
print(trace_of_a_matrix)

15


Here,the diagonal elements of the matrix are 1,5,9.
Therefore the trace=1+5+9=15

##### 3.diagonal():

Diagonal: Diagonal Prints the diagonal elements of a matrix and return them as a 1D array.

In [44]:
diagonal_matrix = np.diagonal(array)
print(diagonal_matrix)

[1 5 9]


##### matmul():

Matrix Multiplication: Multiply two matrices.

In [82]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_mult = np.matmul(matrix1, matrix2)
print(matrix_mult)

[[19 22]
 [43 50]]


#### Concatenation:
##### concatenate():

Concatenate: It combine arrays along an existing axis(if axis=0 combines along the rows , axis=1 combines along the columns).

In [46]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
#combines along rows
concatenated_array = np.concatenate((array1, array2), axis=0) 
print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Combine along rows
concatenated_array = np.concatenate((array1, array2), axis=1)  
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


#### Stacking:
Stacking: Combine arrays along a new axis

##### vstack():

Vertical Stacking:Used to stack the sequence of input arrays vertically (ie row wise) to make a single array.


In [50]:
vstacked_array = np.vstack((array1, array2))  
print(vstacked_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##### hstack():

Horizontal Stacking : Used to stack the sequence of input arrays horizontally (ie column wise) to make a single array.

In [51]:
hstacked_array = np.hstack((array1, array2))  
print(hstacked_array)

[[1 2 5 6]
 [3 4 7 8]]


#### Splitting Arrays:

Split: Split an array into multiple sub-arrays.

In [54]:
array = np.arange(9).reshape((3, 3))
split_array = np.split(array, 3)  
print(split_array)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


##### vsplit():

Vertical Splits:Used to spilt the input array vertically (ie row wise) into a multiple sub-arrays.

In [55]:
vsplit_array = np.vsplit(array, 3) 
print(vsplit_array)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


##### hsplit():

Horizontal Splits:Used to spilt the input array horizontally (ie row wise) into a multiple sub-arrays.

In [56]:
hsplit_array = np.hsplit(array, 3) 
print(hsplit_array)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


#### Element-wise Operations:
Arithmetic Operations: Perform element-wise addition, subtraction, multiplication, and division and returns the result asa an array.

##### Addition:

In [57]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2 
# Element-wise addition
print(sum_array)

[5 7 9]


##### Subtraction:

In [58]:
diff_array = array1 - array2 
# Element-wise subtraction
print(diff_array)

[-3 -3 -3]


##### Multiplication:

In [59]:
product_array = array1 * array2 
# Element-wise multiplication
print(product_array)

[ 4 10 18]


##### Division:

In [60]:
quotient_array = array1 / array2
# Element-wise division
print(quotient_array)

[0.25 0.4  0.5 ]


Universal Functions (ufuncs): Apply mathematical functions element-wise.

##### Square root:

In [61]:
sqrt_array = np.sqrt(array1)  
# Square root of each element
print(sqrt_array)

[1.         1.41421356 1.73205081]


##### Exponential:

In [62]:
exp_array = np.exp(array1) 
# Exponential of each element
print(exp_array)

[ 2.71828183  7.3890561  20.08553692]


#### Boolean Indexing and Filtering:
Boolean Indexing: Select elements based on conditions . If the condition is true then it returns the value . Otherwise it reurns null.

In [64]:
array = np.array([1, 2, 3, 4, 5])
filtered_array = array[array > 2] 
print(filtered_array)

[3 4 5]


Conditional Operations: Use np.where() for condition-based operations. If the condition is true then it returns the value . Otherwise it reurns 0.

In [66]:
result_array = np.where(array > 2, array, 0) 
print(result_array)

[0 0 3 4 5]


#### Sorting and Searching:
Sort: Sort an array.

In [68]:
array = np.array([3, 1, 2])
#sort in ascending order
sorted_array = np.sort(array) 
print(sorted_array)

[1 2 3]


Argsort: Get the indices that would sort an array.

In [69]:
indices = np.argsort(array) 
# Indices of the sorted array
print(indices)

[1 2 0]


Searchsorted: Find indices where elements should be inserted to maintain order.

In [71]:
indices = np.searchsorted(sorted_array, 2) 
# Index where 2 should be inserted
print(indices)

1


## Aggregation and Statistical Functions:
##### sum():

Sum:Sum returns the sum of the elements in the array. 

In [72]:
array = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(array)
print(total_sum)

15


##### mean():

Mean:It returns the arithmetic mean of the elements present in the array.
     
      mean=(sum of all elements)/(no.of elements)

In [73]:
mean_value = np.mean(array)
print(mean_value)

3.0


##### median():

Median:It returns the middle value of the sorted array.

In [74]:
median = np.median(array)
print(median)

3.0


##### std():

Standard Deviation:It returns the standard deviation of the array elements.

In [76]:
std_deviation = np.std(array)
print(std_deviation)

1.4142135623730951


##### min():

Minimum : It returns the minimum value present in the input array elements.

In [77]:
min_value = np.min(array)
print(min_value)

1


##### max():

Maximum : It returns the minimum value present in the input array elements.

In [78]:
max_value = np.max(array)
print(max_value)

5


##### argmin():

Argmin : It returns the index of the minimum value of the given array

In [80]:
min_index = np.argmin(array)
print(min_index)

0


##### argmax():

Argmax : It returns the index of the minimum value of the given array.

In [81]:
max_index = np.argmax(array)
print(max_index)

4


##### Broadcasting:

Broadcasting: Perform operations on each element present yn the input arrays of different shapes

In [84]:
array = np.array([1, 2, 3])
broadcasted_result = array + 10  # Adds 10 to each element
print(broadcasted_result)

[11 12 13]


##### dot():

Dot Product: Calculate the dot product of two arrays.

In [86]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])
dot_product = np.dot(array1, array2) 
# 1*3 + 2*4 = 11
print(dot_product)

11


##### Data Type Conversion:

Change Data Type: Convert the data type of an array

In [88]:
array = np.array([1.1, 2.2, 3.3])
int_array = array.astype(int) 
# Convert to integer array
print(int_array)

[1 2 3]


### Analyzing the data using numpy:
##### Correlation Analysis
Correlation analysis helps to determine the relationship between two or more variables. The Pearson correlation coefficient is a common measure of linear correlation.

In [8]:
#two variables, X and Y, representing the scores in two different subjects.
X = np.array([85, 90, 78, 92, 88])
Y = np.array([80, 85, 77, 89, 84])
# Calculate Pearson correlation coefficient
correlation_matrix = np.corrcoef(X, Y)
correlation_coefficient = correlation_matrix[0, 1]
print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.9580416299057327


### Outlier Detection
Outliers are data points that differ significantly from other observations. Detecting outliers can be done using Z-scores or the IQR (Interquartile Range) method.

##### 1.Using Z-scores:
A Z-score represents the number of standard deviations a data point is from the mean. Typically, a Z-score greater than 3 or less than -3 is considered an outlier.

In [12]:
# Calculate the mean and standard deviation
mean_X = np.mean(X)
std_X = np.std(X)
# Calculate Z-scores
z_scores = (X - mean_X) / std_X
# Identify outliers (Z-score > 1 or < -1)
outliers = X[np.abs(z_scores) > 1]

print("Outliers:", outliers)


Outliers: [78 92]


##### 2.Using the IQR Method:
The IQR method detects outliers by measuring the spread of the middle 50% of the data.

In [15]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = np.percentile(X, 25)
Q3 = np.percentile(X, 75)
IQR = Q3 - Q1
# Determine the lower and upper bounds for outliers
lower_bound = Q1 - 0.5 * IQR
upper_bound = Q3 + 0.5 * IQR
# Identify outliers
outliers_iqr = X[(X < lower_bound) | (X > upper_bound)]
print("Outliers using IQR:", outliers_iqr)

Outliers using IQR: [78]


## Applications of Analyzing the data using numpy:

#### 1.Machine Learning:
Data Preprocessing: NumPy helps in handling and manipulating large datasets, such as normalizing or transforming features.

Matrix Operations: Essential for implementing machine learning algorithms that rely on linear algebra, such as neural networks and clustering algorithms.

Performance: Offers fast and efficient computations which are crucial for training models on large datasets.
#### Financial Analysis:
Data Analysis: Enables the analysis of financial data, such as stock prices, and the calculation of statistical measures like moving averages and volatility.
Risk Management: Helps in modeling and simulations, including Monte Carlo simulations for forecasting and risk assessment.
Optimization: Used in portfolio optimization and other financial computations that involve matrix operations.
#### Scientific Research:
Numerical Simulations: Facilitates simulations in physics, engineering, and other scientific fields where matrix operations and mathematical computations are required.
Data Analysis: Assists in analyzing experimental data, performing statistical analyses, and visualizing results.
Interoperability: Integrates well with other scientific libraries like SciPy and Pandas, enhancing its utility in complex research workflows.

#### Analyzing Daily Temperatures:

Problem Statement:

Suppose we have a dataset containing daily temperature readings for a city over a year , and you want to perform various analyses such as calculaing the average temperature , finding the hottest and coldest days , and identifying days with temperatures above a certain threshold.

Steps to follow:

##### 1.Loading and Exploring Data:


In [2]:
import numpy as np

In [3]:
#Example : daily temperatures (in celsius) over a year
temp = np.array([22.1,23.5,21.7,20.3,25.1,30.2,28.4,24.5,19.8,21.0,23.7,27.2])

##### Saving array to files:

In [4]:
np.save('temp.npy', temp)

##### Loading them to back:

In [5]:
loaded_array = np.load('temp.npy')

##### calculating the mean temperature:

To find average temperature over the year.

In [6]:
mean_temp = np.mean(temp)
print(f"average temperature over the year:{mean_temp:.2f}c")

average temperature over the year:23.96c


##### Finding minimum and maximum temperatures over the year:

To determine the hottest and coldest days over the year.

In [19]:
max_temp = np.max(temp)
print(f"the maximum temperature recored in the year is:{max_temp:.2f}c")
min_temp = np.min(temp)
print(f"the minimum temperature recored in the year is:{min_temp:.2f}c")

the maximum temperature recored in the year is:30.20c
the minimum temperature recored in the year is:19.80c


##### Identifying days above a certain threshold:

To find all days where the temperature above 27c using boolean indexing.

In [20]:
hot_days = temp[temp>27]
print(f"days with temperature above 27c is :{hot_days}")

days with temperature above 27c is :[30.2 28.4 27.2]


##### Performing vectorized operations:

Numpy allows to perform operations on entire arrays without the need for explicit loops , making the code faster and more concise.

In [21]:
f_temp = (temp * 9/5) +32
print(f"Temperatures in Fahrenheit:{f_temp}")

Temperatures in Fahrenheit:[71.78 74.3  71.06 68.54 77.18 86.36 83.12 76.1  67.64 69.8  74.66 80.96]


#### Predicting House Prices:

Problem Statement:

Suppose you are working on a project to predict house prices based on features such as the size of the house, the number of bedrooms, the number of 
bathrooms, and the distance to the city center. You have a dataset containing these features for several houses, along with their actual prices. 
Our goal is to build a model to predict the price of a house given its features.

Steps to follow:

##### 1.Loading and Exploring Data:
    
First, you'll load the data and explore it to understand its structure.

In [22]:
import numpy as np

In [23]:
# Example data: size (sqft), number of bedrooms, number of bathrooms, distance to city center (miles),Prices are in thousands of dollars
data = np.array([
    [2100, 3, 2, 10, 400],
    [1600, 2, 1, 15, 330],
    [2400, 4, 3, 5, 540],
    [1410, 3, 1, 20, 280],
    [3000, 4, 4, 2, 610],
])

Saving to files:

In [24]:
np.save('data.npy', data)

Loading them to back:

In [25]:
loaded_array = np.load('data.npy')

Splitting of data:

In [26]:
# Split the data into features (X) and target (y)
X = data[:, :-1]  # All rows, all columns except the last one
y = data[:, -1]   # All rows, only the last column

##### 2.Data Preprocessing:

Often, data needs to be normalized or standardized before feeding it into a machine learning model. This step ensures that all features contribute equally to the model

In [27]:
# Normalizing the feature data
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_normalized = (X - X_mean) / X_std

##### 3.Building a Simple Linear Model:
   
Let's assume you want to create a simple linear regression model to predict house prices. While sophisticated libraries like scikit-learn can be used, we'll demonstrate this manually using NumPy.

In [28]:
# Add a bias term (intercept) to the feature matrix
X_bias = np.c_[np.ones(X_normalized.shape[0]), X_normalized]

# Initialize weights (coefficients), including the intercept
weights = np.random.rand(X_bias.shape[1])

# Define a function to calculate predictions
def predict(X, weights):
    return np.dot(X, weights)

# Define a loss function (Mean Squared Error)
def compute_loss(X, y, weights):
    predictions = predict(X, weights)
    errors = predictions - y
    return np.mean(errors**2)

# Gradient Descent to optimize weights
learning_rate = 0.01
num_iterations = 1000

for i in range(num_iterations):
    predictions = predict(X_bias, weights)
    errors = predictions - y
    gradient = 2 * np.dot(X_bias.T, errors) / len(y)
    weights -= learning_rate * gradient

    if i % 100 == 0:
        loss = compute_loss(X_bias, y, weights)
        print(f"Iteration {i}, Loss: {loss:.4f}")

# Final weights
print("Final weights:", weights)

Iteration 0, Loss: 192174.7803
Iteration 100, Loss: 3439.1997
Iteration 200, Loss: 306.5426
Iteration 300, Loss: 237.0190
Iteration 400, Loss: 228.7231
Iteration 500, Loss: 223.9911
Iteration 600, Loss: 220.2723
Iteration 700, Loss: 217.0234
Iteration 800, Loss: 214.0618
Iteration 900, Loss: 211.3146
Final weights: [431.99999927  25.77260169  10.64432756  37.52697124 -52.95765092]


##### 4.Making Predictions:

Once the model is trained, you can use it to predict the price of a new house.

In [29]:
# Example new house features (size, bedrooms, bathrooms, distance)
new_house = np.array([2000, 3, 2, 8])

# Normalize the new house features
new_house_normalized = (new_house - X_mean) / X_std

# Add bias term
new_house_bias = np.insert(new_house_normalized, 0, 1)

# Predict the price
predicted_price = predict(new_house_bias, weights)
print(f"Predicted price of the new house: ${predicted_price:.2f}K")


Predicted price of the new house: $437.57K


#### Advantages of Numpy in data science:

##### Efficiency: 
NumPy is highly optimized for numerical computation, making it faster than standard Python lists and loops.

##### Flexibility:
It provides a range of functions for mathematical operations, data reshaping, and manipulation.

##### Interoperability:
NumPy arrays are the foundation for many other data science libraries (e.g., Pandas, scikit-learn), making it easy to integrate into larger data pipelines.